#!/usr/bin/env python
# — coding: utf-8 —
from editor import Editor
editor = Editor()

tool_types = ["เครื่องมือตัด/เจาะ", "เครื่องมือขันยึด", "เครื่องมือวัด", "เครื่องมือจับยึด", "เครื่องมือตอก", "เครื่องเชื่อม/อุปกรณ์", "เครื่องมือกลไฟฟ้า", "อุปกรณ์ทำความสะอาด", "อุปกรณ์ป้องกัน (safety)"]
editor.tool.create_new_tool("เลื่อยตัดเหล็ก", tool_types[0], "", 10, 10, "") # name, tool_type, description, total, in_stock, picture
editor.tool.create_new_tool("เลื่อยฉลุ", tool_types[0], "", 11, 11, "")
editor.tool.create_new_tool("กรรไกรตัดแผ่นโลหะ", tool_types[0], "", 2, 2, "")
editor.tool.create_new_tool("ตะไบละเอียด ขนาด 10-12 นิ้ว แบน", tool_types[0], "", 4, 4, "")
editor.tool.create_new_tool("ตะไบละเอียด ขนาด 10-12 นิ้ว กลม", tool_types[0], "", 5, 5, "")
editor.tool.create_new_tool("ตะไบละเอียด ขนาด 10-12 นิ้ว ท้องปลิง", tool_types[0], "", 5, 5, "")
editor.tool.create_new_tool("ชุดตะไบละเอียด ขนาด 4 นิ้ว ( แบน/กลม/สี่เหลี่ยม/สามเหลี่ยม/ท้องปลิง )", tool_types[0], "", 10, 10, "")
editor.tool.create_new_tool("ดอกสว่าน ขนาด ø 1 - 13 mm.", tool_types[0], "", 2, 2, "")
editor.tool.create_new_tool("ดอกเจาะนำศูนย์ ø 1 mm.", tool_types[0], "", 1, 1, "")
editor.tool.create_new_tool("ดอกเจาะนำศูนย์ ø 3 mm.", tool_types[0], "", 1, 1, "")
editor.tool.create_new_tool("ดอกเจาะนำศูนย์ ø 2 mm.", tool_types[0], "", 1, 1, "")
editor.tool.create_new_tool("ดอกต๊าป  ขนาด  M 3 x 0.5 mm.", tool_types[0], "", 4, 4, "")
editor.tool.create_new_tool("ดอกต๊าป  ขนาด  M 4 x 0.7 mm.", tool_types[0], "", 4, 4, "")
editor.tool.create_new_tool("ดอกต๊าป  ขนาด  M 5 x 0.8 mm.", tool_types[0], "", 2, 2, "")
editor.tool.create_new_tool("ดอกต๊าป  ขนาด  M 6 x 1.0 mm.", tool_types[0], "", 3, 3, "")
editor.tool.create_new_tool("ดอกต๊าป  ขนาด  M 8 x 1.25 mm.", tool_types[0], "", 3, 3, "")
editor.tool.create_new_tool("ชุดประแจแหวนข้างปากตาย ( 8-24 mm.)", tool_types[1], "", 2, 2, "")
editor.tool.create_new_tool("ชุดประแจแหวนข้างปากตาย ( inch.)", tool_types[1], "", 1, 1, "")
editor.tool.create_new_tool("ชุดประแจแหวน     ( 6-32 mm.)", tool_types[1], "", 1, 1, "")
editor.tool.create_new_tool("ชุดประแจหกเหลี่ยมสั้น    ( mm.)", tool_types[1], "", 2, 2, "")
editor.tool.create_new_tool("ชุดประแจหกเหลี่ยมยาว หัวบอล  ( mm.)", tool_types[1], "", 5, 5, "")
editor.tool.create_new_tool("ชุดประแจหกเหลี่ยมยาว หัวบอล  ( inch.)", tool_types[1], "", 1, 1, "")
editor.tool.create_new_tool("ชุดไขควงปากแบน/ปากแฉก   ( เล็ก กลาง ใหญ่ )", tool_types[1], "", 50, 50, "")
editor.tool.create_new_tool("ชุดไขควงกระแทรก", tool_types[1], "", 1, 1, "")
editor.tool.create_new_tool("คีมยิงรีเวท", tool_types[1], "", 8, 8, "")
editor.tool.create_new_tool("ประแจเลื่อน 8\"", tool_types[1], "", 1, 1, "")
editor.tool.create_new_tool("ประแจเลื่อน 10\"", tool_types[1], "", 1, 1, "")
editor.tool.create_new_tool("ประแจเลื่อน 12\"", tool_types[1], "", 1, 1, "")
editor.tool.create_new_tool("ประแจเลื่อน 18\"", tool_types[1], "", 1, 1, "")
editor.tool.create_new_tool("ประแจจับแป๊บ 1 1/2\"", tool_types[1], "", 1, 1, "")
editor.tool.create_new_tool("ชุดลูกบ๊อกซ์ ขนาด 1/2\" No.10-32 mm.", tool_types[1], "", 1, 1, "")
editor.tool.create_new_tool("ชุดลูกบ๊อกซ์ ขนาด 1\" No.", tool_types[1], "", 1, 1, "")
editor.tool.create_new_tool("ด้ามต๊าป (ใหญ่)", tool_types[1], "", 1, 1, "")
editor.tool.create_new_tool("ด้ามต๊าป (เล็ก)", tool_types[1], "", 2, 2, "")
editor.tool.create_new_tool("ตลับเมตร  7.5 เมตร", tool_types[2], "", 1, 1, "")
editor.tool.create_new_tool("ตลับเมตร    5 เมตร", tool_types[2], "", 4, 4, "")
editor.tool.create_new_tool("บรรทัดเหล็ก 12\"", tool_types[2], "", 15, 15, "")
editor.tool.create_new_tool("บรรทัดเหล็ก 1 เมตร", tool_types[2], "", 2, 2, "")
editor.tool.create_new_tool("ระดับน้ำ 9\"", tool_types[2], "", 3, 3, "")
editor.tool.create_new_tool("ระดับน้ำ 1 เมตร", tool_types[2], "", 1, 1, "")
editor.tool.create_new_tool("ฉากเหล็ก", tool_types[2], "", 3, 3, "")
editor.tool.create_new_tool("ฉากงานไม้", tool_types[2], "", 2, 2, "")
editor.tool.create_new_tool("เวอร์เนียร์คาลิปเปอร์ 8\"", tool_types[2], "", 5, 5, "")
editor.tool.create_new_tool("บรรทัดวัดองศา", tool_types[2], "", 2, 2, "")
editor.tool.create_new_tool("คีมปากตรง (6\")", tool_types[3], "", 3, 3, "")
editor.tool.create_new_tool("คีมปากตรง (8\")", tool_types[3], "", 2, 2, "")
editor.tool.create_new_tool("คีมปากขยาย (8\")", tool_types[3], "", 5, 5, "")
editor.tool.create_new_tool("คีมตัด", tool_types[3], "", 4, 4, "")
editor.tool.create_new_tool("คีมปากแหลม", tool_types[3], "", 4, 4, "")
editor.tool.create_new_tool("คีมคอม้า", tool_types[3], "", 2, 2, "")
editor.tool.create_new_tool("คีมหนีบแหวน", tool_types[3], "", 2, 2, "")
editor.tool.create_new_tool("คีมถ่างแหวน", tool_types[3], "", 3, 3, "")
editor.tool.create_new_tool("คีมล็อคปากตรง", tool_types[3], "", 8, 8, "")
editor.tool.create_new_tool("คีมล็อครูปตัวซี", tool_types[3], "", 2, 2, "")
editor.tool.create_new_tool("ปากกาจับชิ้นงาน 6\"", tool_types[3], "", 4, 4, "")
editor.tool.create_new_tool("ปากกาจับชิ้นงาน 2 1/2\"(หัวโต๊ะ)", tool_types[3], "", 10, 10, "")
editor.tool.create_new_tool("ปากกาจับชิ้นงาน ( เล็ก )", tool_types[3], "", 1, 1, "")
editor.tool.create_new_tool("C-Clamp 3\"", tool_types[3], "", 7, 7, "")
editor.tool.create_new_tool("C-Clamp 4\"", tool_types[3], "", 8, 8, "")
editor.tool.create_new_tool("C-Clamp 6\"", tool_types[3], "", 2, 2, "")
editor.tool.create_new_tool("C-Clamp 8\"", tool_types[3], "", 2, 2, "")
editor.tool.create_new_tool("Workbench", tool_types[3], "", 2, 2, "")
editor.tool.create_new_tool("ค้อนเหล็กหัวกลม (1.5 ปอนด์)", tool_types[4], "", 5, 5, "")
editor.tool.create_new_tool("ค้อนเหล็กช่างไม้", tool_types[4], "", 5, 5, "")
editor.tool.create_new_tool("ค้อนยาง", tool_types[4], "", 5, 5, "")
editor.tool.create_new_tool("เหล็กตอกนำศูนย์", tool_types[4], "", 2, 2, "")
editor.tool.create_new_tool("เหล็กสกัด 1\"", tool_types[4], "", 2, 2, "")
editor.tool.create_new_tool("เครื่องเชื่อมไฟฟ้า (Long Well 270 P)", tool_types[5], "", 1, 1, "")
editor.tool.create_new_tool("ตู้เชื่อม 300 Amp.", tool_types[5], "", 1, 1, "")
editor.tool.create_new_tool("ตู้เชื่อม 150 Amp.", tool_types[5], "", 1, 1, "")
editor.tool.create_new_tool("ถังอาร์กอน (6 คิว)", tool_types[5], "", 1, 1, "")
editor.tool.create_new_tool("หน้ากากเชื่อมแบบปรับแสงอัตโนมัติ (LongWell)", tool_types[5], "", 1, 1, "")
editor.tool.create_new_tool("หน้ากากเชื่อมแบบปรับแสงอัตโนมัติ", tool_types[5], "", 1, 1, "")
editor.tool.create_new_tool("หน้ากากเชื่อมแบบธรรมดา", tool_types[5], "", 1, 1, "")
editor.tool.create_new_tool("แว่นตางานเชื่อม", tool_types[5], "", 1, 1, "")
editor.tool.create_new_tool("ถุงมือเชื่อม", tool_types[5], "", 2, 2, "")
editor.tool.create_new_tool("หินเจียรไฟฟ้า ( ø 4\")", tool_types[6], "", 1, 1, "")
editor.tool.create_new_tool("สว่านไฟฟ้า (เล็ก)", tool_types[6], "", 1, 1, "")
editor.tool.create_new_tool("สว่านไฟฟ้า", tool_types[6], "", 2, 2, "")
editor.tool.create_new_tool("สว่านโรตารี่ (ใหญ่)", tool_types[6], "", 1, 1, "")
editor.tool.create_new_tool("สว่านโรตารี่ (เล็ก)", tool_types[6], "", 1, 1, "")
editor.tool.create_new_tool("สว่านแบตเตอร์รี่ (ไร้สาย)", tool_types[6], "", 2, 2, "")
editor.tool.create_new_tool("ไฟเบอร์ตัดเหล็ก 14\" ( ø 355 mm.)", tool_types[6], "", 1, 1, "")
editor.tool.create_new_tool("เลื่อยวงเดือน", tool_types[6], "", 1, 1, "")
editor.tool.create_new_tool("เลื่อยจิ๊กซอไฟฟ้า (BOSCH)", tool_types[6], "", 1, 1, "")
editor.tool.create_new_tool("เลื่อยจิ๊กซอไฟฟ้า (V-master)", tool_types[6], "", 3, 3, "")
editor.tool.create_new_tool("ปั๊มลม", tool_types[6], "", 1, 1, "")
editor.tool.create_new_tool("หินเจียรไฟฟ้าแบบตั้งโต๊ะ  8\"  ", tool_types[6], "", 1, 1, "")
editor.tool.create_new_tool("ด้ามเฟืองกรอหินเจียร", tool_types[6], "", 1, 1, "")
editor.tool.create_new_tool("เครื่องเลื่อย  16 \"", tool_types[6], "", 1, 1, "")
editor.tool.create_new_tool("สว่านแท่น   (เล็ก)", tool_types[6], "", 6, 6, "")
editor.tool.create_new_tool("สว่านแท่น   (ใหญ่)", tool_types[6], "", 2, 2, "")
editor.tool.create_new_tool("แปรงทาสี (ใช้ปัดเศษโลหะ)  2 นิ้ว", tool_types[7], "", 5, 5, "")
editor.tool.create_new_tool("แปรงทองเหลือง (ใช้ขัดตะไบ)", tool_types[7], "", 5, 5, "")
editor.tool.create_new_tool("กาน้ำมัน", tool_types[7], "", 5, 5, "")
editor.tool.create_new_tool("แว่นตากันเศษโลหะ", tool_types[8], "", 10, 10, "")
editor.tool.create_new_tool("หมวกนิรภัย", tool_types[8], "", 4, 4, "")
print(editor.tool.list_all())